In [ ]:
# Import libraries
import numpy as np
import pandas as pd
import matplotlib.pyplot as plt
from sklearn.preprocessing import LabelEncoder, OneHotEncoder
from sklearn.cross_validation import train_test_split


"""
# Import data set
dataset = pd.read_csv('default of credit card clients.csv', header=1)
del rawData ['ID']
rawData.rename(columns = {'default payment next month':'default'}, inplace=True)
dataset
#X = dataset.iloc[:, :-1].values
#y = dataset.iloc[:, 3].values


# Encoding categorical data i.e. change yes/no and France/Spain/Germany
from sklearn.preprocessing import LabelEncoder, OneHotEncoder
onehotencoder = OneHotEncoder(categorical_features = [0])
X = onehotencoder.fit_transform(X).toarray().astype(int)
                      
# Change Purchased labels
labelencoder_y = LabelEncoder()
y = labelencoder_y.fit_transform(y)"""

"""# Splitting data set into Training and Testing
from sklearn.cross_validation import train_test_split
X_train, X_test, y_train, y_test = train_test_split(X, y, test_size = .20, random_state = 0)"""

"""# Feature scaling
from sklearn.preprocessing import StandardScaler
sc_X = StandardScaler()
X_train = sc_X.fit_transform(X_train)
X_test = sc_X.transform(X_test)  #transform only

# Fitting the regression model to the data set
# Create regressor here
""" 

In [22]:
# Import libraries
import numpy as np
import pandas as pd
import matplotlib.pyplot as plt
from sklearn.preprocessing import LabelEncoder, OneHotEncoder
from sklearn.cross_validation import train_test_split

In [23]:
# Import data 
dataset = pd.read_csv('default of credit card clients.csv', header=1)
del dataset ['ID']
dataset.rename(columns = {'default payment next month':'default'}, inplace=True)
dataset[0:10]
dataset.shape
X = dataset.iloc[:, :-1].values
y = dataset.iloc[:, 23].values

In [24]:
dataset.iloc[0:3,10:23]

PAY_6  BILL_AMT1  BILL_AMT2  BILL_AMT3  BILL_AMT4  BILL_AMT5  BILL_AMT6  \
0     -2       3913       3102        689          0          0          0   
1      2       2682       1725       2682       3272       3455       3261   
2      0      29239      14027      13559      14331      14948      15549   

   PAY_AMT1  PAY_AMT2  PAY_AMT3  PAY_AMT4  PAY_AMT5  PAY_AMT6  
0         0       689         0         0         0         0  
1         0      1000      1000      1000         0      2000  
2      1518      1500      1000      1000      1000      5000

In [25]:
X[0:3]

array([[ 20000,      2,      2,      1,     24,      2,      2,     -1,
            -1,     -2,     -2,   3913,   3102,    689,      0,      0,
             0,      0,    689,      0,      0,      0,      0],
       [120000,      2,      2,      2,     26,     -1,      2,      0,
             0,      0,      2,   2682,   1725,   2682,   3272,   3455,
          3261,      0,   1000,   1000,   1000,      0,   2000],
       [ 90000,      2,      2,      2,     34,      0,      0,      0,
             0,      0,      0,  29239,  14027,  13559,  14331,  14948,
         15549,   1518,   1500,   1000,   1000,   1000,   5000]],
      dtype=int64)

In [26]:
y

array([1, 1, 0, ..., 1, 1, 1], dtype=int64)

In [27]:
# Splitting data set into Training and Testing
from sklearn.cross_validation import train_test_split
X_train, X_test, y_train, y_test = train_test_split(X, y, test_size = 1/3, random_state = 0)

In [28]:
X_train

array([[300000,      2,      1, ...,  78794,   2900,   3000],
       [ 50000,      1,      2, ...,    105,   2300,   1600],
       [ 20000,      1,      3, ...,      0,      0,      0],
       ...,
       [130000,      2,      3, ...,   4100,      0,   5000],
       [ 50000,      2,      3, ...,   1000,   1000,    500],
       [140000,      2,      1, ...,   2000,   2200,   2000]], dtype=int64)

# Multiple Linear Regression #

In [29]:
# Fitting Multiple Linear Regression to the Training Set
from sklearn.linear_model import LinearRegression
regressor = LinearRegression()
regressor.fit(X_train, y_train)

LinearRegression(copy_X=True, fit_intercept=True, n_jobs=1, normalize=False)

In [30]:
# Predicting the Test set results
y_pred = regressor.predict(X_test).astype(int)
y_pred

array([0, 0, 0, ..., 0, 0, 0])

In [31]:
# Backward Elimination Preparation
import statsmodels.formula.api as sm
X = np.append(arr = np.ones((30000,1)).astype(int), values = X, axis = 1)
X[3,], len(X[1])

(array([    1, 50000,     2,     2,     1,    37,     0,     0,     0,
            0,     0,     0, 46990, 48233, 49291, 28314, 28959, 29547,
         2000,  2019,  1200,  1100,  1069,  1000], dtype=int64), 24)

In [32]:
# Start Backward Elimination
# Create optimized matrix
X_opt = X[:, [0, 1, 2, 3, 4, 5, 6, 7, 8, 9, 10, 11, 12, 13, 14, 15, 16, 17, 18, 19, 20, 21, 22,23]]
#            [c,x1,x2,x3,x4,x5,x6,x7,x8,x9,x10,x11,x12,x13,x14,x15,x16,x17,x18,x19,x20,x21,x22,x23]

# Select significance level : SL = 0.05
# Fit model with all possible predictors - use new regressor
regressor_OLS = sm.OLS(endog = y, exog = X_opt).fit()
regressor_OLS.summary()

<class 'statsmodels.iolib.summary.Summary'>
"""
                            OLS Regression Results                            
==============================================================================
Dep. Variable:                      y   R-squared:                       0.124
Model:                            OLS   Adj. R-squared:                  0.123
Method:                 Least Squares   F-statistic:                     184.5
Date:                Thu, 25 Oct 2018   Prob (F-statistic):               0.00
Time:                        22:40:56   Log-Likelihood:                -14202.
No. Observations:               30000   AIC:                         2.845e+04
Df Residuals:                   29976   BIC:                         2.865e+04
Df Model:                          23                                         
Covariance Type:            nonrobust                                         
==============================================================================
                 coef    std err          t      P>|t|      [0.025      0.975]
------------------------------------------------------------------------------
const          0.3142      0.018     17.541      0.000       0.279       0.349
x1         -9.053e-08   2.16e-08     -4.193      0.000   -1.33e-07   -4.82e-08
x2            -0.0145      0.005     -3.130      0.002      -0.024      -0.005
x3            -0.0151      0.003     -5.022      0.000      -0.021      -0.009
x4            -0.0238      0.005     -4.996      0.000      -0.033      -0.014
x5             0.0014      0.000      5.128      0.000       0.001       0.002
x6             0.0957      0.003     34.596      0.000       0.090       0.101
x7             0.0195      0.003      5.828      0.000       0.013       0.026
x8             0.0117      0.004      3.256      0.001       0.005       0.019
x9             0.0034      0.004      0.846      0.398      -0.004       0.011
x10            0.0057      0.004      1.324      0.185      -0.003       0.014
x11            0.0008      0.004      0.225      0.822      -0.006       0.008
x12        -6.225e-07   1.14e-07     -5.453      0.000   -8.46e-07   -3.99e-07
x13         1.587e-07    1.6e-07      0.990      0.322   -1.56e-07    4.73e-07
x14         3.005e-08   1.51e-07      0.199      0.842   -2.66e-07    3.26e-07
x15        -6.793e-08   1.57e-07     -0.432      0.666   -3.76e-07     2.4e-07
x16        -2.049e-08   1.85e-07     -0.111      0.912   -3.82e-07    3.41e-07
x17         1.153e-07   1.46e-07      0.789      0.430   -1.71e-07    4.02e-07
x18        -7.437e-07   1.77e-07     -4.201      0.000   -1.09e-06   -3.97e-07
x19        -2.092e-07   1.46e-07     -1.436      0.151   -4.95e-07    7.63e-08
x20        -2.874e-08   1.69e-07     -0.170      0.865    -3.6e-07    3.02e-07
x21        -2.521e-07   1.84e-07     -1.371      0.170   -6.13e-07    1.08e-07
x22         -3.41e-07   1.91e-07     -1.787      0.074   -7.15e-07     3.3e-08
x23         -9.77e-08   1.37e-07     -0.716      0.474   -3.65e-07     1.7e-07
==============================================================================
Omnibus:                     4682.286   Durbin-Watson:                   2.013
Prob(Omnibus):                  0.000   Jarque-Bera (JB):             7285.821
Skew:                           1.204   Prob(JB):                         0.00
Kurtosis:                       3.178   Cond. No.                     2.10e+06
==============================================================================

Warnings:
[1] Standard Errors assume that the covariance matrix of the errors is correctly specified.
[2] The condition number is large, 2.1e+06. This might indicate that there are
strong multicollinearity or other numerical problems.
"""

In [33]:
X_opt.shape[1], X_opt[3, 0:23]

(24, array([    1, 50000,     2,     2,     1,    37,     0,     0,     0,
            0,     0,     0, 46990, 48233, 49291, 28314, 28959, 29547,
         2000,  2019,  1200,  1100,  1069], dtype=int64))

In [ ]:
# Remove X16 or col 16
X_opt = X[:, [0, 1, 2, 3, 4, 5, 6, 7, 8, 9, 10, 11, 12, 13, 14, 15, 17, 18, 19, 20, 21, 22, 23]]
#            [c,x1,x2,x3,x4,x5,x6,x7,x8,x9,x10,x11,x12,x13,x14,x15,x16,x17,x18,x19,x20,x21,x22]

# Fit model without X2 predictors
regressor_OLS = sm.OLS(endog = y, exog = X_opt).fit()
regressor_OLS.summary()

In [ ]:
X_opt.shape[1], X_opt[3, 0:23]

In [35]:
# Remove X19 or col 19
X_opt = X[:, [0, 1, 2, 3, 4, 5, 6, 7, 8, 12, 18]]

# Fit model without X2 or X1 predictors
regressor_OLS = sm.OLS(endog = y, exog = X_opt).fit()
regressor_OLS.summary()

<class 'statsmodels.iolib.summary.Summary'>
"""
                            OLS Regression Results                            
==============================================================================
Dep. Variable:                      y   R-squared:                       0.123
Model:                            OLS   Adj. R-squared:                  0.123
Method:                 Least Squares   F-statistic:                     421.4
Date:                Thu, 25 Oct 2018   Prob (F-statistic):               0.00
Time:                        22:49:46   Log-Likelihood:                -14216.
No. Observations:               30000   AIC:                         2.845e+04
Df Residuals:                   29989   BIC:                         2.854e+04
Df Model:                          10                                         
Covariance Type:            nonrobust                                         
==============================================================================
                 coef    std err          t      P>|t|      [0.025      0.975]
------------------------------------------------------------------------------
const          0.3133      0.018     17.495      0.000       0.278       0.348
x1         -1.105e-07   2.08e-08     -5.309      0.000   -1.51e-07   -6.97e-08
x2            -0.0143      0.005     -3.080      0.002      -0.023      -0.005
x3            -0.0153      0.003     -5.075      0.000      -0.021      -0.009
x4            -0.0240      0.005     -5.041      0.000      -0.033      -0.015
x5             0.0014      0.000      5.138      0.000       0.001       0.002
x6             0.0974      0.003     35.537      0.000       0.092       0.103
x7             0.0201      0.003      6.071      0.000       0.014       0.027
x8             0.0178      0.003      5.983      0.000       0.012       0.024
x9         -4.587e-07   3.45e-08    -13.315      0.000   -5.26e-07   -3.91e-07
x10        -7.858e-07    1.4e-07     -5.616      0.000   -1.06e-06   -5.12e-07
==============================================================================
Omnibus:                     4682.501   Durbin-Watson:                   2.013
Prob(Omnibus):                  0.000   Jarque-Bera (JB):             7285.027
Skew:                           1.204   Prob(JB):                         0.00
Kurtosis:                       3.182   Cond. No.                     1.80e+06
==============================================================================

Warnings:
[1] Standard Errors assume that the covariance matrix of the errors is correctly specified.
[2] The condition number is large, 1.8e+06. This might indicate that there are
strong multicollinearity or other numerical problems.
"""

In [40]:
X_opt.shape
X = X_opt

In [41]:
# Splitting data set into Training and Testing
from sklearn.cross_validation import train_test_split
X_train, X_test, y_train, y_test = train_test_split(X, y, test_size = .20, random_state = 0)

In [42]:
# Import estimators
from sklearn.ensemble import RandomForestClassifier, GradientBoostingClassifier
from sklearn.linear_model import LogisticRegression
from sklearn.svm import SVC
from sklearn.neighbors import KNeighborsClassifier
from sklearn.discriminant_analysis import LinearDiscriminantAnalysis

# Import model metrics
from sklearn.metrics import classification_report
from sklearn.metrics import accuracy_score
from sklearn.model_selection import cross_val_score

# Import cross validation
from sklearn.cross_validation import train_test_split

In [43]:
# Models
modelKNN = KNeighborsClassifier()
modelRF = RandomForestClassifier()
modelGB = GradientBoostingClassifier()
modelLOG = LogisticRegression()
modelSVC = SVC()

In [44]:
# Model fitting - KNN
modelKNN.fit(X_train, y_train)
print(cross_val_score(modelKNN, X_train, y_train))
modelKNN.score(X_train, y_train)

[0.74565679 0.746375   0.74221778]


0.811875

In [45]:
# Model fitting - RF
modelRF.fit(X_train, y_train)
print(cross_val_score(modelRF, X_train, y_train))
modelRF.score(X_train, y_train)

[0.80177478 0.795125   0.80297537]


0.977

In [46]:
# Model fitting - GB
modelGB.fit(X_train, y_train)
print(cross_val_score(modelGB, X_train, y_train))
modelGB.score(X_train, y_train)

[0.81852268 0.818125   0.81560195]


0.821875

In [47]:
# Model fitting - LOG
modelLOG.fit(X_train, y_train)
print(cross_val_score(modelLOG, X_train, y_train))
modelLOG.score(X_train, y_train)

[0.77752781 0.7775     0.7775972 ]


0.7775416666666667

In [48]:
# Model fitting - SVC
modelSVC.fit(X_train, y_train)
print(cross_val_score(modelSVC, X_train, y_train))
modelSVC.score(X_train, y_train)

[0.7767779  0.776      0.77747218]


0.9898333333333333

In [49]:
# Make predictions - RF
predictions = modelRF.predict(X_test)
predAccuracy = accuracy_score(y_test, predictions)
print(classification_report(y_test, predictions))
print('Random Forest Metrics:')
print('Accurancy: %.3f' % predAccuracy)

             precision    recall  f1-score   support

          0       0.83      0.93      0.88      4703
          1       0.55      0.32      0.41      1297

avg / total       0.77      0.80      0.78      6000

Random Forest Metrics:
Accurancy: 0.798


In [50]:
# Make predictions - SVC
predictions = modelSVC.predict(X_test)
predAccuracy = accuracy_score(y_test, predictions)
print(classification_report(y_test, predictions))
print('SVR Metrics:')
print('Accuracy: %.3f' % predAccuracy)

             precision    recall  f1-score   support

          0       0.79      1.00      0.88      4703
          1       0.51      0.02      0.03      1297

avg / total       0.73      0.78      0.70      6000

SVR Metrics:
Accuracy: 0.784


In [51]:
# Make predictions - GB
predictions = modelGB.predict(X_test)
predAccuracy = accuracy_score(y_test, predictions)
print(classification_report(y_test, predictions))
print('GB Metrics:')
print('Accuracy: %.3f' % predAccuracy)

             precision    recall  f1-score   support

          0       0.85      0.96      0.90      4703
          1       0.71      0.36      0.48      1297

avg / total       0.82      0.83      0.81      6000

GR Metrics:
Accuracy: 0.830


In [54]:
# Make predictions - KNN
predictions = modelLOG.predict(X_test)
predAccuracy = accuracy_score(y_test, predictions)
print(classification_report(y_test, predictions))
print('KNN Metrics:')
print('Accuracy: %.3f' % predAccuracy)

             precision    recall  f1-score   support

          0       0.78      1.00      0.88      4703
          1       0.00      0.00      0.00      1297

avg / total       0.61      0.78      0.69      6000

KNN Metrics:
Accuracy: 0.784


C:\Users\Christy McCanless\Anaconda3\lib\site-packages\sklearn\metrics\classification.py:1135: UndefinedMetricWarning: Precision and F-score are ill-defined and being set to 0.0 in labels with no predicted samples.
  'precision', 'predicted', average, warn_for)
